spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/drone?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    static-path-pattern: /static/**
  servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 10000MB
server:
  servlet:
    context-path: /bigfile


